
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
 build-angular:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pigeon-sky-race-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Run E2E tests
        run: npx cypress run
