name: CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # - name: Run unit tests
      #   run: npm test
      #   working-directory: ./frontend

      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./frontend

      # - name: Run E2E tests
      #   run: npx cypress run
      #   working-directory: ./frontend